# Column/variable names used as bare symbols inside dplyr/tidyr NSE calls
# throughout the package (data-mask lookups R CMD check's static analysis
# cannot resolve). Listed here, rather than converted to `.data$`/`.env$`
# everywhere, because most of these sit in functions untouched by 0.10.2
# (see dev/claude_code_prompt_0.10.2_bugfixes.md Part 7); code touched
# this release already uses `.data$` instead. Exactly the names `R CMD
# check` reports, sorted.
utils::globalVariables(c(
  ".actor1",
  ".flag",
  ".threshold",
  ".year",
  "action_index",
  "actor_a",
  "actor_b",
  "base_name",
  "bin",
  "class_label",
  "contraction",
  "contribution_obs",
  "contribution_ratio",
  "contribution_rep",
  "country_index",
  "cumulative_loss_mean",
  "d_alpha",
  "dyad",
  "dyad_id",
  "dyad2",
  "ess_bulk",
  "ess_flag",
  "ess_tail",
  "event_type",
  "filter_index",
  "flagged",
  "idx",
  "index_1",
  "index_2",
  "info_share",
  "is_side_a_sender",
  "label_a",
  "label_b",
  "loss_mean",
  "median",
  "merged_a",
  "merged_b",
  "n",
  "n_dt",
  "n_remaining",
  "pct_info_lost",
  "post_mean",
  "post_sd",
  "q5",
  "q95",
  "rhat",
  "rhat_flag",
  "share",
  "step",
  "tier",
  "time_index",
  "total_events",
  "variable",
  "worse_than_expected",
  "z_score"
))
